In [2]:
#imports
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt


from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix

from sklearn import tree
from sklearn.ensemble import RandomForestRegressor

import sklearn

import CHAID

In [3]:
train_data = pd.read_csv("2023_DS2_HW1_data_train.csv")

In [4]:
train_data

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN10204,NaN,NaN,NaN,2.0,Meal Plan 2,NaN,Room_Type 6,NaN,2018.0,9.0,NaN,Online,0.0,0.0,NaN,NaN,1.0,0.0
1,INN20020,NaN,NaN,NaN,2.0,Meal Plan 1,NaN,NaN,NaN,NaN,12.0,NaN,Online,0.0,0.0,0.0,NaN,NaN,0.0
2,INN16435,1.0,NaN,NaN,2.0,NaN,0.0,Room_Type 1,NaN,2018.0,11.0,NaN,NaN,0.0,0.0,NaN,NaN,1.0,0.0
3,INN07143,3.0,NaN,NaN,3.0,NaN,NaN,NaN,100.0,2018.0,5.0,NaN,Online,0.0,0.0,NaN,NaN,2.0,0.0
4,INN20511,1.0,0.0,1.0,1.0,Meal Plan 1,0.0,NaN,NaN,2018.0,11.0,NaN,NaN,0.0,0.0,0.0,150.0,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32642,INN16851,2.0,NaN,NaN,NaN,Meal Plan 1,NaN,NaN,43.0,2017.0,12.0,26.0,Offline,NaN,0.0,0.0,NaN,2.0,0.0
32643,INN06266,1.0,NaN,NaN,2.0,Meal Plan 2,0.0,Room_Type 1,102.0,2017.0,10.0,NaN,Online,NaN,0.0,NaN,80.0,NaN,1.0
32644,INN11285,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2018.0,5.0,NaN,Corporate,0.0,0.0,0.0,NaN,1.0,0.0
32645,INN00861,2.0,NaN,NaN,3.0,Meal Plan 1,0.0,NaN,NaN,2018.0,6.0,NaN,Online,NaN,0.0,NaN,NaN,0.0,1.0
32646,INN15796,2.0,NaN,NaN,2.0,NaN,NaN,NaN,14.0,2018.0,9.0,15.0,Online,NaN,0.0,NaN,NaN,NaN,0.0

In [5]:
data_cart = train_data.copy()
data_cart.isna().sum()

Booking_ID                                  0
no_of_adults                             4416
no_of_children                          27604
no_of_weekend_nights                    24918
no_of_week_nights                        8360
type_of_meal_plan                       16103
required_car_parking_space              14784
room_type_reserved                      21287
lead_time                               25712
arrival_year                             2993
arrival_month                             907
arrival_date                            27190
market_segment_type                     14121
repeated_guest                          24978
no_of_previous_cancellations               69
no_of_previous_bookings_not_canceled    14621
avg_price_per_room                      23589
no_of_special_requests                   7450
booking_status                            352
dtype: int64

In [6]:
data_cart.dtypes

Booking_ID                               object
no_of_adults                            float64
no_of_children                          float64
no_of_weekend_nights                    float64
no_of_week_nights                       float64
type_of_meal_plan                        object
required_car_parking_space              float64
room_type_reserved                       object
lead_time                               float64
arrival_year                            float64
arrival_month                           float64
arrival_date                            float64
market_segment_type                      object
repeated_guest                          float64
no_of_previous_cancellations            float64
no_of_previous_bookings_not_canceled    float64
avg_price_per_room                      float64
no_of_special_requests                  float64
booking_status                          float64
dtype: object

In [7]:
data_cart.fillna(value= -1, inplace=True)
data_cart = data_cart[data_cart['booking_status'] != -1]

In [8]:
#TBD: pridat 'type_of_meal_plan','room_type_reserved',market_segment_type',

target = 'booking_status'

predictors = [ 'no_of_adults', 'no_of_children', 'no_of_weekend_nights',
       'no_of_week_nights',  'required_car_parking_space',
        'lead_time', 'arrival_year', 'arrival_month',
       'arrival_date', 'repeated_guest',
       'no_of_previous_cancellations', 'no_of_previous_bookings_not_canceled',
       'avg_price_per_room', 'no_of_special_requests']

In [9]:
data_cart_train, data_cart_test = train_test_split(
    data_cart, test_size=0.2, random_state=17
)

In [28]:
criterion = 'gini' #(TODO)
splitter = 'best' #(TODO)
mdepth = 20 #(TODO)
min_samples_split = 5 #(TODO)
min_samples_leaf = 0.001 #(TODO)
minleaf = 100 #(TODO)
random_state = 17


model = tree.DecisionTreeClassifier(
    criterion=criterion,
    splitter=splitter, 
    max_depth=mdepth,
    min_samples_split=min_samples_split,
    min_samples_leaf=min_samples_leaf, 
    random_state=random_state, 
)

In [29]:

# And fit training data.

clf = model.fit(data_cart_train[predictors], data_cart_train['booking_status'])

In [12]:
xxx

NameError: name 'xxx' is not defined

In [30]:
pred_labels_tr = model.predict(data_cart_train[predictors])
pred_labels_te = model.predict(data_cart_test[predictors])

In [31]:
# Tree summary and model evaluation metrics
print('*************** Tree Summary ***************')
print('Classes: ', clf.classes_)
print('Tree Depth: ', clf.tree_.max_depth)
print('No. of leaves: ', clf.tree_.n_leaves)
print('No. of features: ', clf.n_features_)
print('--------------------------------------------------------')
print("")

print('*************** Evaluation on Test Data ***************')
score_te = model.score(data_cart_test[predictors], data_cart_test[target])
print('Accuracy Score: ', score_te)
# Look at classification report to evaluate the model
print(classification_report(data_cart_test[target], pred_labels_te))
print('--------------------------------------------------------')
print("")

print('*************** Evaluation on Training Data ***************')
score_tr = model.score(data_cart_train[predictors], data_cart_train[target])
print('Accuracy Score: ', score_tr)
# Look at classification report to evaluate the model
print(classification_report(data_cart_train[target], pred_labels_tr))
print('--------------------------------------------------------')

*************** Tree Summary ***************
Classes:  [0. 1.]
Tree Depth:  20
No. of leaves:  678
No. of features:  14
--------------------------------------------------------

*************** Evaluation on Test Data ***************
Accuracy Score:  0.725499303297724
              precision    recall  f1-score   support

         0.0       0.75      0.88      0.81      4323
         1.0       0.63      0.42      0.50      2136

    accuracy                           0.73      6459
   macro avg       0.69      0.65      0.66      6459
weighted avg       0.71      0.73      0.71      6459

--------------------------------------------------------

*************** Evaluation on Training Data ***************
Accuracy Score:  0.758283015946741
              precision    recall  f1-score   support

         0.0       0.78      0.89      0.83     17451
         1.0       0.68      0.48      0.56      8385

    accuracy                           0.76     25836
   macro avg       0.73      0.68      0.70     25836
weighted avg       0.75      0.76      0.74     25836

--------------------------------------------------------

In [ ]:
fig, ax = plt.subplots(figsize=(25, 25))
tree.plot_tree(clf, ax=ax)
plt.show()

In [ ]:
data_cart_test['Prediction_prob'] = clf.predict_proba(data_cart_test[predictors])[:,1] #(TODO)
data_cart_test['Prediction'] = (data_cart_test['Prediction_prob']>=0.5).astype(int) #(TODO)




data_cart_train['Prediction_prob'] = clf.predict_proba(data_cart_train[predictors])[:,1] #(TODO)
data_cart_train['Prediction'] = (data_cart_train['Prediction_prob']>=0.5).astype(int) #(TODO)

In [ ]:
conf_mx = pd.DataFrame(sklearn.metrics.confusion_matrix(data_cart_test["booking_status"], data_cart_test['Prediction']))
conf_mx
#v řádku predikce, v sloupci realita

In [ ]:
# Get numerical feature importances
importances = list(clf.feature_importances_)
# List of tuples with variable and importance
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(predictors, importances)]
# Sort the feature importances by most important first
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)
# Print out the feature and importances 
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances];

In [ ]:
# Plot importance
x_values = list(range(len(importances)))
# Make a bar chart
plt.bar(x_values, importances, orientation = 'vertical')
# Tick labels for x axis
plt.xticks(x_values, predictors, rotation='vertical')
# Axis labels and title
plt.ylabel('Importance'); plt.xlabel('Variable'); plt.title('Variable Importances');

In [ ]:
fpr, tpr, thresholds = roc_curve(data_cart_test["booking_status"], data_cart_test['Prediction_prob'])
plt.plot(fpr, tpr)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.show()


auc = roc_auc_score(data_cart_test["booking_status"], data_cart_test['Prediction_prob'])
print("AUC:", auc)

# adding artificial variables

In [23]:
#here we will add combination of variables 

data_cart_new = train_data.copy()
data_cart_new = data_cart_new[[ 'no_of_adults', 'no_of_children', 'no_of_weekend_nights',
       'no_of_week_nights',  'required_car_parking_space',
        'lead_time', 'arrival_year', 'arrival_month',
       'arrival_date', 'repeated_guest',
       'no_of_previous_cancellations', 'no_of_previous_bookings_not_canceled',
       'avg_price_per_room', 'no_of_special_requests','booking_status']].copy()
data_cart_new

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,required_car_parking_space,lead_time,arrival_year,arrival_month,arrival_date,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,NaN,NaN,NaN,2.0,NaN,NaN,2018.0,9.0,NaN,0.0,0.0,NaN,NaN,1.0,0.0
1,NaN,NaN,NaN,2.0,NaN,NaN,NaN,12.0,NaN,0.0,0.0,0.0,NaN,NaN,0.0
2,1.0,NaN,NaN,2.0,0.0,NaN,2018.0,11.0,NaN,0.0,0.0,NaN,NaN,1.0,0.0
3,3.0,NaN,NaN,3.0,NaN,100.0,2018.0,5.0,NaN,0.0,0.0,NaN,NaN,2.0,0.0
4,1.0,0.0,1.0,1.0,0.0,NaN,2018.0,11.0,NaN,0.0,0.0,0.0,150.0,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32642,2.0,NaN,NaN,NaN,NaN,43.0,2017.0,12.0,26.0,NaN,0.0,0.0,NaN,2.0,0.0
32643,1.0,NaN,NaN,2.0,0.0,102.0,2017.0,10.0,NaN,NaN,0.0,NaN,80.0,NaN,1.0
32644,2.0,NaN,NaN,2.0,NaN,NaN,2018.0,5.0,NaN,0.0,0.0,0.0,NaN,1.0,0.0
32645,2.0,NaN,NaN,3.0,0.0,NaN,2018.0,6.0,NaN,NaN,0.0,NaN,NaN,0.0,1.0
32646,2.0,NaN,NaN,2.0,NaN,14.0,2018.0,9.0,15.0,NaN,0.0,NaN,NaN,NaN,0.0

In [24]:
data_cart_new.fillna(value= -1, inplace=True)
data_cart_new = data_cart_new[data_cart_new['booking_status'] != -1]
data_cart_new

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,required_car_parking_space,lead_time,arrival_year,arrival_month,arrival_date,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,-1.0,-1.0,-1.0,2.0,-1.0,-1.0,2018.0,9.0,-1.0,0.0,0.0,-1.0,-1.0,1.0,0.0
1,-1.0,-1.0,-1.0,2.0,-1.0,-1.0,-1.0,12.0,-1.0,0.0,0.0,0.0,-1.0,-1.0,0.0
2,1.0,-1.0,-1.0,2.0,0.0,-1.0,2018.0,11.0,-1.0,0.0,0.0,-1.0,-1.0,1.0,0.0
3,3.0,-1.0,-1.0,3.0,-1.0,100.0,2018.0,5.0,-1.0,0.0,0.0,-1.0,-1.0,2.0,0.0
4,1.0,0.0,1.0,1.0,0.0,-1.0,2018.0,11.0,-1.0,0.0,0.0,0.0,150.0,-1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32642,2.0,-1.0,-1.0,-1.0,-1.0,43.0,2017.0,12.0,26.0,-1.0,0.0,0.0,-1.0,2.0,0.0
32643,1.0,-1.0,-1.0,2.0,0.0,102.0,2017.0,10.0,-1.0,-1.0,0.0,-1.0,80.0,-1.0,1.0
32644,2.0,-1.0,-1.0,2.0,-1.0,-1.0,2018.0,5.0,-1.0,0.0,0.0,0.0,-1.0,1.0,0.0
32645,2.0,-1.0,-1.0,3.0,0.0,-1.0,2018.0,6.0,-1.0,-1.0,0.0,-1.0,-1.0,0.0,1.0
32646,2.0,-1.0,-1.0,2.0,-1.0,14.0,2018.0,9.0,15.0,-1.0,0.0,-1.0,-1.0,-1.0,0.0

In [25]:
data_cart_new_results = data_cart_new[["booking_status"]]
data_cart_new = data_cart_new.drop('booking_status', axis=1)
data_cart_new

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,required_car_parking_space,lead_time,arrival_year,arrival_month,arrival_date,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests
0,-1.0,-1.0,-1.0,2.0,-1.0,-1.0,2018.0,9.0,-1.0,0.0,0.0,-1.0,-1.0,1.0
1,-1.0,-1.0,-1.0,2.0,-1.0,-1.0,-1.0,12.0,-1.0,0.0,0.0,0.0,-1.0,-1.0
2,1.0,-1.0,-1.0,2.0,0.0,-1.0,2018.0,11.0,-1.0,0.0,0.0,-1.0,-1.0,1.0
3,3.0,-1.0,-1.0,3.0,-1.0,100.0,2018.0,5.0,-1.0,0.0,0.0,-1.0,-1.0,2.0
4,1.0,0.0,1.0,1.0,0.0,-1.0,2018.0,11.0,-1.0,0.0,0.0,0.0,150.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32642,2.0,-1.0,-1.0,-1.0,-1.0,43.0,2017.0,12.0,26.0,-1.0,0.0,0.0,-1.0,2.0
32643,1.0,-1.0,-1.0,2.0,0.0,102.0,2017.0,10.0,-1.0,-1.0,0.0,-1.0,80.0,-1.0
32644,2.0,-1.0,-1.0,2.0,-1.0,-1.0,2018.0,5.0,-1.0,0.0,0.0,0.0,-1.0,1.0
32645,2.0,-1.0,-1.0,3.0,0.0,-1.0,2018.0,6.0,-1.0,-1.0,0.0,-1.0,-1.0,0.0
32646,2.0,-1.0,-1.0,2.0,-1.0,14.0,2018.0,9.0,15.0,-1.0,0.0,-1.0,-1.0,-1.0